version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-microservice
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - APP_NAME=go-microservice
      - LOG_LEVEL=debug
      - DB_DSN=postgres://postgres:postgres@postgres:5432/microservice?sslmode=disable
      - METRICS_ENABLED=true
      - CORS_ENABLED=true
      - CORS_ALLOWED_ORIGINS=*
      - RATE_LIMITER_ENABLED=true
      - RATE_LIMITER_REQUESTS_PER_SECOND=20
      - RATE_LIMITER_BURST=30
      - RATE_LIMITER_STRATEGY=ip
    volumes:
      - .:/app
    depends_on:
      - postgres
      
  postgres:
    image: postgres:15-alpine
    container_name: microservice-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=microservice
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      
  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: microservice-pgadmin
  #   restart: unless-stopped
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=admin@example.com
  #     - PGADMIN_DEFAULT_PASSWORD=admin
  #   ports:
  #     - "5050:80"
  #   depends_on:
  #     - postgres
  
volumes:
  postgres_data: